### ISSUE TITLE
Can't build in Xcode

### ISSUE THREAD

**Issue by nicholasalanbrown** [buildreactnative/assemblies#8]
When trying to build the project in Xcode after following the steps in the README, I get this in my Terminal:

```
React packager ready.

[3:16:33 PM] <END>   Crawling File System (3065ms)
[3:16:33 PM] <START> Building in-memory fs for JavaScript
[3:16:36 PM] <END>   Building in-memory fs for JavaScript (3212ms)
[3:16:36 PM] <START> Building in-memory fs for Assets
[3:16:38 PM] <END>   Building in-memory fs for Assets (2483ms)
[3:16:38 PM] <START> Building Haste Map
[3:16:41 PM] <START> Building (deprecated) Asset Map
[3:16:42 PM] <END>   Building (deprecated) Asset Map (1224ms)
Error building DependencyGraph:
 Error: Naming collision detected: /Users/nbrown/Source/assemblies/node_modules/react/node_modules/fbjs/lib/warning.js collides with /Users/nbrown/Source/assemblies/node_modules/react-native/node_modules/fbjs/lib/warning.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:103:28
    at tryCallOne (/Users/nbrown/Source/assemblies/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/nbrown/Source/assemblies/node_modules/react-native/node_modules/promise/lib/core.js:123:15
    at flush (/Users/nbrown/Source/assemblies/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

**Comment by nicholasalanbrown** [comment]
Now I'm getting a different error, this time trying with `react-native v0.19.0`:

![image](https://cloud.githubusercontent.com/assets/3259022/14196266/a96a5fea-f790-11e5-9758-9a54a91fd71b.png)

**Comment by nicholasalanbrown** [comment]
Anyone who's having the `naming collision detected` issue, I was able to resolve mine with `sudo npm install npm -g`, then blowing away the `node_modules` directory, then running `npm install`. 

As for the red screen of death, I only got that upon updating `react-native`. We'll handle updates in a branch, test, and merge in soon.

**Comment by balibou** [comment]
Thanks @nicholasalanbrown !
